/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConversationView: typeof import('./components/conversation/ConversationView.vue')['default']
    DoctorCard: typeof import('./components/doctor/DoctorCard.vue')['default']
    DoctorConsultationDialog: typeof import('./components/conversation/DoctorConsultationDialog.vue')['default']
    DoctorList: typeof import('./components/doctor/DoctorList.vue')['default']
    DoctorMetricsDashboard: typeof import('./components/doctor/DoctorMetricsDashboard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ExaminationCard: typeof import('./components/medical/ExaminationCard.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    MessageBubble: typeof import('./components/conversation/MessageBubble.vue')['default']
    MetricsChart: typeof import('./components/doctor/MetricsChart.vue')['default']
    PatientCard: typeof import('./components/patient/PatientCard.vue')['default']
    PatientEvaluationCard: typeof import('./components/doctor/PatientEvaluationCard.vue')['default']
    PatientList: typeof import('./components/patient/PatientList.vue')['default']
    PatientTrajectory: typeof import('./components/patient/PatientTrajectory.vue')['default']
    ProfileCard: typeof import('./components/patient/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    StatusTimeline: typeof import('./components/patient/StatusTimeline.vue')['default']
    TagList: typeof import('./components/common/TagList.vue')['default']
    TreatmentCard: typeof import('./components/medical/TreatmentCard.vue')['default']
  }
}
